Data Pipeline for Server Monitoring Dataset

In [6]:
from google.colab import files
uploaded = files.upload()

Saving Sample_Data_Ingestion.csv to Sample_Data_Ingestion (1).csv

Data Ingestion

In [7]:
import pandas as pd
df = pd.read_csv("Sample_Data_Ingestion.csv")
df.head()

,Server_ID,Hostname,IP_Address,OS_Type,Server_Location,CPU_Utilization (%),Memory_Usage (%),Disk_IO (%),Network_Traffic_In (MB/s),Network_Traffic_Out (MB/s),Uptime (Hours),Downtime (Hours),Admin_Name,Admin_Email,Admin_Phone,Log_Timestamp
0,536c9e75-40a1-4a74-8ca6-c6abaec13999,srv-web02,100.33.3.46,Windows Server 2022,"Berlin, Germany",28.10,88.60,28.36,31.13,52.54,18.49,5.51,John Duarte,laurasolomon@example.net,+77 1834560143,11-03-2025 16:45
1,26bae71d-c025-4082-9484-ef7aa9e04836,srv-web02,249.168.171.15,Ubuntu 20.04,"London, UK",49.72,84.35,73.89,123.34,97.10,19.71,4.29,Abigail Montgomery,sherripatterson@example.com,+10 3791349757,25-01-2025 10:59
2,454de38a-5961-490f-9d46-d20663a36baf,srv-backup02,248.247.52.48,Red Hat Enterprise Linux,"New York, USA",44.72,57.64,14.94,69.60,112.81,18.64,5.36,David Jones,veronicanavarro@example.net,+38 9503876034,29-01-2025 08:31
3,8b8a3f40-1b67-4fe6-a65e-93fd07f317f7,srv-web02,87.221.187.138,Red Hat Enterprise Linux,"New York, USA",37.69,97.97,71.46,62.97,148.51,18.14,5.86,Dominic Richards,frankdawson@example.org,+93 2330701744,01-03-2025 16:49
4,375cb3db-89d3-4705-af4a-8f829cce1928,srv-app02,168.8.91.217,Windows Server 2022,"Tokyo, Japan",63.97,67.31,96.46,45.33,131.50,22.78,1.22,Paul Edwards,hgibson@example.com,+29 9075330226,21-02-2025 11:02

Data Quality Checks

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Server_ID                   200 non-null    object
 1   Hostname                    200 non-null    object
 2   IP_Address                  200 non-null    object
 3   OS_Type                     200 non-null    object
 4   Server_Location             200 non-null    object
 5   CPU_Utilization (%)         200 non-null    float64
 6   Memory_Usage (%)            200 non-null    float64
 7   Disk_IO (%)                 200 non-null    float64
 8   Network_Traffic_In (MB/s)   200 non-null    float64
 9   Network_Traffic_Out (MB/s)  200 non-null    float64
 10  Uptime (Hours)              200 non-null    float64
 11  Downtime (Hours)            200 non-null    float64
 12  Admin_Name                  200 non-null    object
 13  Admin_Email                 200 non-null    object
 14  Admin_Phone                 200 non-null    object
 15  Log_Timestamp               200 non-null    object
dtypes: float64(7), object(9)
memory usage: 25.1+ KB

In [9]:
df.isnull().sum()

Server_ID                     0
Hostname                      0
IP_Address                    0
OS_Type                       0
Server_Location               0
CPU_Utilization (%)           0
Memory_Usage (%)              0
Disk_IO (%)                   0
Network_Traffic_In (MB/s)     0
Network_Traffic_Out (MB/s)    0
Uptime (Hours)                0
Downtime (Hours)              0
Admin_Name                    0
Admin_Email                   0
Admin_Phone                   0
Log_Timestamp                 0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.head(15)

,Server_ID,Hostname,IP_Address,OS_Type,Server_Location,CPU_Utilization (%),Memory_Usage (%),Disk_IO (%),Network_Traffic_In (MB/s),Network_Traffic_Out (MB/s),Uptime (Hours),Downtime (Hours),Admin_Name,Admin_Email,Admin_Phone,Log_Timestamp
0,536c9e75-40a1-4a74-8ca6-c6abaec13999,srv-web02,100.33.3.46,Windows Server 2022,"Berlin, Germany",28.10,88.60,28.36,31.13,52.54,18.49,5.51,John Duarte,laurasolomon@example.net,+77 1834560143,11-03-2025 16:45
1,26bae71d-c025-4082-9484-ef7aa9e04836,srv-web02,249.168.171.15,Ubuntu 20.04,"London, UK",49.72,84.35,73.89,123.34,97.10,19.71,4.29,Abigail Montgomery,sherripatterson@example.com,+10 3791349757,25-01-2025 10:59
2,454de38a-5961-490f-9d46-d20663a36baf,srv-backup02,248.247.52.48,Red Hat Enterprise Linux,"New York, USA",44.72,57.64,14.94,69.60,112.81,18.64,5.36,David Jones,veronicanavarro@example.net,+38 9503876034,29-01-2025 08:31
3,8b8a3f40-1b67-4fe6-a65e-93fd07f317f7,srv-web02,87.221.187.138,Red Hat Enterprise Linux,"New York, USA",37.69,97.97,71.46,62.97,148.51,18.14,5.86,Dominic Richards,frankdawson@example.org,+93 2330701744,01-03-2025 16:49
4,375cb3db-89d3-4705-af4a-8f829cce1928,srv-app02,168.8.91.217,Windows Server 2022,"Tokyo, Japan",63.97,67.31,96.46,45.33,131.50,22.78,1.22,Paul Edwards,hgibson@example.com,+29 9075330226,21-02-2025 11:02
5,9a90becd-5be4-4d03-b1fa-1ffa70cb11f5,srv-app02,142.229.13.87,Ubuntu 20.04,"Tokyo, Japan",20.29,24.65,66.56,60.59,133.97,18.68,5.32,Thomas Pearson,monicamartinez@example.org,+41 5610383316,13-02-2025 19:44
6,c2ba6509-caa4-4720-8633-cb7565e9947c,srv-app03,143.148.212.7,Ubuntu 20.04,"Sydney, Australia",36.45,59.28,18.46,47.70,86.57,22.38,1.62,Richard Goodman,sarah65@example.com,+77 4103444382,09-03-2025 14:58
7,8e52d19d-1e84-466e-8e25-d24ae27434ab,srv-web01,147.18.138.45,Ubuntu 20.04,"Tokyo, Japan",12.62,86.98,18.54,102.76,11.03,20.30,3.70,Jessica Day,sheri42@example.org,+75 8001044687,06-03-2025 10:06
8,95de17b4-60ec-4ea0-a79c-7faecdb85275,srv-app03,157.114.125.79,CentOS 8,"Sydney, Australia",75.49,73.48,93.03,29.02,22.00,20.49,3.51,Stephanie Petersen,kevin33@example.org,+71 9513511325,24-02-2025 14:29
9,4aa1fa83-c575-4d81-a1c7-f1ed5395a0f6,srv-analytics01,186.179.201.0,CentOS 8,"Tokyo, Japan",88.30,24.14,25.99,67.86,120.95,20.19,3.81,Aaron Marquez MD,darrenklein@example.net,+98 6695197615,20-02-2025 18:41
10,28fe2731-7083-4dd0-97aa-e535ecd8842f,srv-api02,69.186.115.145,CentOS 8,"Berlin, Germany",12.99,58.45,27.97,72.81,122.67,19.96,4.04,Samantha Allen,vpearson@example.com,+23 9648157051,18-02-2025 03:53
11,c2596d33-afee-434c-ac03-a277135eabdd,srv-api03,17.220.229.32,Windows Server 2019,"London, UK",41.71,59.25,36.54,22.89,86.55,22.89,1.11,Allen Collins,perezrachel@example.com,+49 8574002766,14-02-2025 14:24
12,c137b910-3675-4dbd-9353-3ba607e98cb0,srv-backup01,167.128.117.110,Windows Server 2019,"Sydney, Australia",55.22,68.63,10.85,28.02,11.73,20.64,3.36,James Stewart,stephenbarnes@example.net,+49 6568170313,15-01-2025 21:24
13,b2607e67-2bd4-4a90-a786-212775f24f61,srv-analytics02,113.228.208.191,Ubuntu 20.04,"New York, USA",86.03,27.24,90.44,112.72,90.19,21.86,2.14,Jesse Ho,ppaul@example.net,+97 3930225486,25-01-2025 21:29
14,08ac5795-9603-4848-9fc0-f20307b026aa,srv-cache03,245.43.251.158,Ubuntu 20.04,"London, UK",17.66,79.55,13.41,67.99,71.75,18.49,5.51,Thomas Schmitt,cherylgrant@example.net,+20 7885197158,07-02-2025 18:43

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Log_Timestamp"] = pd.to_datetime(df["Log_Timestamp"], dayfirst=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Server_ID                   200 non-null    object
 1   Hostname                    200 non-null    object
 2   IP_Address                  200 non-null    object
 3   OS_Type                     200 non-null    object
 4   Server_Location             200 non-null    object
 5   CPU_Utilization (%)         200 non-null    float64
 6   Memory_Usage (%)            200 non-null    float64
 7   Disk_IO (%)                 200 non-null    float64
 8   Network_Traffic_In (MB/s)   200 non-null    float64
 9   Network_Traffic_Out (MB/s)  200 non-null    float64
 10  Uptime (Hours)              200 non-null    float64
 11  Downtime (Hours)            200 non-null    float64
 12  Admin_Name                  200 non-null    object
 13  Admin_Email                 200 non-null    object
 14  Admin_Phone                 200 non-null    object
 15  Log_Timestamp               200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(7), object(8)
memory usage: 25.1+ KB

Data Transformation

In [15]:
df["Total_Network_Traffic"] = df["Network_Traffic_In (MB/s)"] + df["Network_Traffic_Out (MB/s)"]

In [21]:
df.head(5)

,Server_ID,Hostname,IP_Address,OS_Type,Server_Location,CPU_Utilization (%),Memory_Usage (%),Disk_IO (%),Network_Traffic_In (MB/s),Network_Traffic_Out (MB/s),Uptime (Hours),Downtime (Hours),Admin_Name,Admin_Email,Admin_Phone,Log_Timestamp,Total_Network_Traffic,Availability_Rate,Server_Health_Score
0,536c9e75-40a1-4a74-8ca6-c6abaec13999,srv-web02,100.33.3.46,Windows Server 2022,"Berlin, Germany",28.10,88.60,28.36,31.13,52.54,18.49,5.51,John Duarte,laurasolomon@example.net,+77 1834560143,2025-03-11 16:45:00,83.67,77.041667,53.672
1,26bae71d-c025-4082-9484-ef7aa9e04836,srv-web02,249.168.171.15,Ubuntu 20.04,"London, UK",49.72,84.35,73.89,123.34,97.10,19.71,4.29,Abigail Montgomery,sherripatterson@example.com,+10 3791349757,2025-01-25 10:59:00,220.44,82.125000,32.640
2,454de38a-5961-490f-9d46-d20663a36baf,srv-backup02,248.247.52.48,Red Hat Enterprise Linux,"New York, USA",44.72,57.64,14.94,69.60,112.81,18.64,5.36,David Jones,veronicanavarro@example.net,+38 9503876034,2025-01-29 08:31:00,182.41,77.666667,60.338
3,8b8a3f40-1b67-4fe6-a65e-93fd07f317f7,srv-web02,87.221.187.138,Red Hat Enterprise Linux,"New York, USA",37.69,97.97,71.46,62.97,148.51,18.14,5.86,Dominic Richards,frankdawson@example.org,+93 2330701744,2025-03-01 16:49:00,211.48,75.583333,34.095
4,375cb3db-89d3-4705-af4a-8f829cce1928,srv-app02,168.8.91.217,Windows Server 2022,"Tokyo, Japan",63.97,67.31,96.46,45.33,131.50,22.78,1.22,Paul Edwards,hgibson@example.com,+29 9075330226,2025-02-21 11:02:00,176.83,94.916667,25.281

In [16]:
df["Availability_Rate"] = (df["Uptime (Hours)"] /(df["Uptime (Hours)"] + df["Downtime (Hours)"])) * 100

In [22]:
df.head(2)

,Server_ID,Hostname,IP_Address,OS_Type,Server_Location,CPU_Utilization (%),Memory_Usage (%),Disk_IO (%),Network_Traffic_In (MB/s),Network_Traffic_Out (MB/s),Uptime (Hours),Downtime (Hours),Admin_Name,Admin_Email,Admin_Phone,Log_Timestamp,Total_Network_Traffic,Availability_Rate,Server_Health_Score
0,536c9e75-40a1-4a74-8ca6-c6abaec13999,srv-web02,100.33.3.46,Windows Server 2022,"Berlin, Germany",28.10,88.60,28.36,31.13,52.54,18.49,5.51,John Duarte,laurasolomon@example.net,+77 1834560143,2025-03-11 16:45:00,83.67,77.041667,53.672
1,26bae71d-c025-4082-9484-ef7aa9e04836,srv-web02,249.168.171.15,Ubuntu 20.04,"London, UK",49.72,84.35,73.89,123.34,97.10,19.71,4.29,Abigail Montgomery,sherripatterson@example.com,+10 3791349757,2025-01-25 10:59:00,220.44,82.125000,32.640

In [17]:
df["Server_Health_Score"] = ( 100 - (df["CPU_Utilization (%)"] * 0.4) - (df["Memory_Usage (%)"] * 0.3) - (df["Disk_IO (%)"] * 0.3))

In [18]:
df.head(5)

,Server_ID,Hostname,IP_Address,OS_Type,Server_Location,CPU_Utilization (%),Memory_Usage (%),Disk_IO (%),Network_Traffic_In (MB/s),Network_Traffic_Out (MB/s),Uptime (Hours),Downtime (Hours),Admin_Name,Admin_Email,Admin_Phone,Log_Timestamp,Total_Network_Traffic,Availability_Rate,Server_Health_Score
0,536c9e75-40a1-4a74-8ca6-c6abaec13999,srv-web02,100.33.3.46,Windows Server 2022,"Berlin, Germany",28.10,88.60,28.36,31.13,52.54,18.49,5.51,John Duarte,laurasolomon@example.net,+77 1834560143,2025-03-11 16:45:00,83.67,77.041667,53.672
1,26bae71d-c025-4082-9484-ef7aa9e04836,srv-web02,249.168.171.15,Ubuntu 20.04,"London, UK",49.72,84.35,73.89,123.34,97.10,19.71,4.29,Abigail Montgomery,sherripatterson@example.com,+10 3791349757,2025-01-25 10:59:00,220.44,82.125000,32.640
2,454de38a-5961-490f-9d46-d20663a36baf,srv-backup02,248.247.52.48,Red Hat Enterprise Linux,"New York, USA",44.72,57.64,14.94,69.60,112.81,18.64,5.36,David Jones,veronicanavarro@example.net,+38 9503876034,2025-01-29 08:31:00,182.41,77.666667,60.338
3,8b8a3f40-1b67-4fe6-a65e-93fd07f317f7,srv-web02,87.221.187.138,Red Hat Enterprise Linux,"New York, USA",37.69,97.97,71.46,62.97,148.51,18.14,5.86,Dominic Richards,frankdawson@example.org,+93 2330701744,2025-03-01 16:49:00,211.48,75.583333,34.095
4,375cb3db-89d3-4705-af4a-8f829cce1928,srv-app02,168.8.91.217,Windows Server 2022,"Tokyo, Japan",63.97,67.31,96.46,45.33,131.50,22.78,1.22,Paul Edwards,hgibson@example.com,+29 9075330226,2025-02-21 11:02:00,176.83,94.916667,25.281

Export New Dataset

In [19]:
df.to_csv("new_server_logs.csv", index=False)

In [20]:
from google.colab import files
files.download("new_server_logs.csv")